# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MeetingRoom.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1089, 628)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 110, 1081, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 71, 31))
        self.label_2.setObjectName("label_2")
        self.room_no = QtWidgets.QLineEdit(self.centralwidget)
        self.room_no.setGeometry(QtCore.QRect(150, 70, 113, 20))
        self.room_no.setObjectName("room_no")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 60, 101, 41))
        self.label_3.setObjectName("label_3")
        self.room_capacity = QtWidgets.QLineEdit(self.centralwidget)
        self.room_capacity.setGeometry(QtCore.QRect(450, 70, 113, 20))
        self.room_capacity.setObjectName("room_capacity")
        self.add_room = QtWidgets.QPushButton(self.centralwidget)
        self.add_room.setGeometry(QtCore.QRect(670, 60, 91, 31))
        self.add_room.setObjectName("add_room")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 121, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 180, 71, 31))
        self.label_5.setObjectName("label_5")
        self.meeting_room_no = QtWidgets.QLineEdit(self.centralwidget)
        self.meeting_room_no.setGeometry(QtCore.QRect(150, 180, 113, 20))
        self.meeting_room_no.setObjectName("meeting_room_no")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(390, 170, 41, 41))
        self.label_6.setObjectName("label_6")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 340, 1081, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.meeting_data = QtWidgets.QDateEdit(self.centralwidget)
        self.meeting_data.setGeometry(QtCore.QRect(450, 180, 110, 22))
        self.meeting_data.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 10, 30), QtCore.QTime(0, 0, 0)))
        self.meeting_data.setObjectName("meeting_data")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 230, 71, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(370, 220, 71, 31))
        self.label_8.setObjectName("label_8")
        self.meeting_start_time = QtWidgets.QTimeEdit(self.centralwidget)
        self.meeting_start_time.setGeometry(QtCore.QRect(150, 240, 118, 22))
        self.meeting_start_time.setObjectName("meeting_start_time")
        self.meeting_end_time = QtWidgets.QTimeEdit(self.centralwidget)
        self.meeting_end_time.setGeometry(QtCore.QRect(450, 230, 118, 22))
        self.meeting_end_time.setObjectName("meeting_end_time")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 290, 71, 31))
        self.label_9.setObjectName("label_9")
        self.meeting_linkman = QtWidgets.QLineEdit(self.centralwidget)
        self.meeting_linkman.setGeometry(QtCore.QRect(150, 300, 113, 20))
        self.meeting_linkman.setObjectName("meeting_linkman")
        self.add_meeting = QtWidgets.QPushButton(self.centralwidget)
        self.add_meeting.setGeometry(QtCore.QRect(670, 290, 91, 31))
        self.add_meeting.setObjectName("add_meeting")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 360, 121, 41))
        self.label_10.setObjectName("label_10")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 470, 1081, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 490, 121, 41))
        self.label_11.setObjectName("label_11")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 590, 1081, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.query_meeting_data = QtWidgets.QDateEdit(self.centralwidget)
        self.query_meeting_data.setGeometry(QtCore.QRect(90, 420, 110, 22))
        self.query_meeting_data.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 10, 30), QtCore.QTime(0, 0, 0)))
        self.query_meeting_data.setObjectName("query_meeting_data")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 410, 41, 41))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(360, 410, 71, 31))
        self.label_13.setObjectName("label_13")
        self.query_meeting_room_no = QtWidgets.QLineEdit(self.centralwidget)
        self.query_meeting_room_no.setGeometry(QtCore.QRect(450, 420, 113, 20))
        self.query_meeting_room_no.setObjectName("query_meeting_room_no")
        self.query_meeting = QtWidgets.QPushButton(self.centralwidget)
        self.query_meeting.setGeometry(QtCore.QRect(670, 410, 91, 31))
        self.query_meeting.setObjectName("query_meeting")
        self.query_room_data = QtWidgets.QDateEdit(self.centralwidget)
        self.query_room_data.setGeometry(QtCore.QRect(80, 540, 110, 22))
        self.query_room_data.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 10, 30), QtCore.QTime(0, 0, 0)))
        self.query_room_data.setObjectName("query_room_data")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 530, 41, 41))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(390, 540, 41, 21))
        self.label_15.setObjectName("label_15")
        self.query_room_capacity = QtWidgets.QLineEdit(self.centralwidget)
        self.query_room_capacity.setGeometry(QtCore.QRect(450, 540, 113, 20))
        self.query_room_capacity.setObjectName("query_room_capacity")
        self.query_room = QtWidgets.QPushButton(self.centralwidget)
        self.query_room.setGeometry(QtCore.QRect(670, 540, 91, 31))
        self.query_room.setObjectName("query_room")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(770, 120, 20, 231))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.to_File = QtWidgets.QPushButton(self.centralwidget)
        self.to_File.setGeometry(QtCore.QRect(870, 140, 121, 51))
        self.to_File.setObjectName("to_File")
        self.load_file = QtWidgets.QPushButton(self.centralwidget)
        self.load_file.setGeometry(QtCore.QRect(880, 250, 111, 61))
        self.load_file.setObjectName("load_file")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">添加会议室</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "会议室编号："))
        self.label_3.setText(_translate("MainWindow", "会议室容量（人）："))
        self.add_room.setText(_translate("MainWindow", "添加会议室"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">添加会议</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "会议室编号："))
        self.label_6.setText(_translate("MainWindow", "日期："))
        self.label_7.setText(_translate("MainWindow", "开始时间："))
        self.label_8.setText(_translate("MainWindow", "结束时间："))
        self.label_9.setText(_translate("MainWindow", "联系人："))
        self.add_meeting.setText(_translate("MainWindow", "添加会议"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">查找会议</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">查找会议室</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "日期："))
        self.label_13.setText(_translate("MainWindow", "会议室编号："))
        self.query_meeting.setText(_translate("MainWindow", "查找"))
        self.label_14.setText(_translate("MainWindow", "日期："))
        self.label_15.setText(_translate("MainWindow", "容量："))
        self.query_room.setText(_translate("MainWindow", "查找"))
        self.to_File.setText(_translate("MainWindow", "转储到文件"))
        self.load_file.setText(_translate("MainWindow", "加载文件"))

