# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Auc_UI.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(827, 587)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(363, -60, 20, 951))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 54, 12))
        self.label_4.setObjectName("label_4")
        self.entrust = QtWidgets.QPushButton(self.centralwidget)
        self.entrust.setGeometry(QtCore.QRect(290, 210, 75, 23))
        self.entrust.setObjectName("entrust")
        self.trustee = QtWidgets.QLineEdit(self.centralwidget)
        self.trustee.setGeometry(QtCore.QRect(80, 50, 221, 21))
        self.trustee.setObjectName("trustee")
        self.info = QtWidgets.QTextEdit(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(80, 80, 221, 71))
        self.info.setObjectName("info")
        self.lowest_price = QtWidgets.QLineEdit(self.centralwidget)
        self.lowest_price.setGeometry(QtCore.QRect(80, 170, 221, 21))
        self.lowest_price.setObjectName("lowest_price")
        self.goods_table = QtWidgets.QTableWidget(self.centralwidget)
        self.goods_table.setGeometry(QtCore.QRect(405, 31, 391, 531))
        self.goods_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.goods_table.setDragEnabled(True)
        self.goods_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.goods_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.goods_table.setObjectName("goods_table")
        self.goods_table.setColumnCount(0)
        self.goods_table.setRowCount(0)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-100, 233, 471, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.auction_button = QtWidgets.QPushButton(self.centralwidget)
        self.auction_button.setGeometry(QtCore.QRect(290, 370, 75, 23))
        self.auction_button.setObjectName("auction_button")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 390, 371, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 410, 54, 12))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 400, 61, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(0, 250, 131, 31))
        self.label_7.setObjectName("label_7")
        self.bidder = QtWidgets.QLineEdit(self.centralwidget)
        self.bidder.setGeometry(QtCore.QRect(70, 450, 221, 21))
        self.bidder.setObjectName("bidder")
        self.bid_price = QtWidgets.QLineEdit(self.centralwidget)
        self.bid_price.setGeometry(QtCore.QRect(70, 490, 221, 21))
        self.bid_price.setObjectName("bid_price")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 450, 54, 12))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 490, 54, 12))
        self.label_9.setObjectName("label_9")
        self.bid_button = QtWidgets.QPushButton(self.centralwidget)
        self.bid_button.setGeometry(QtCore.QRect(290, 530, 75, 23))
        self.bid_button.setObjectName("bid_button")
        self.on_auction = QtWidgets.QTableWidget(self.centralwidget)
        self.on_auction.setGeometry(QtCore.QRect(20, 290, 311, 71))
        self.on_auction.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.on_auction.setObjectName("on_auction")
        self.on_auction.setColumnCount(0)
        self.on_auction.setRowCount(0)
        self.end_button = QtWidgets.QPushButton(self.centralwidget)
        self.end_button.setGeometry(QtCore.QRect(200, 530, 75, 23))
        self.end_button.setObjectName("end_button")
        self.bid_info = QtWidgets.QLineEdit(self.centralwidget)
        self.bid_info.setEnabled(False)
        self.bid_info.setGeometry(QtCore.QRect(90, 410, 261, 20))
        self.bid_info.setObjectName("bid_info")
        self.bid_info.setText("起拍价0")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">委托：</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "委托人："))
        self.label_3.setText(_translate("MainWindow", "物品信息："))
        self.label_4.setText(_translate("MainWindow", "保留价："))
        self.entrust.setText(_translate("MainWindow", "委托"))
        self.auction_button.setText(_translate("MainWindow", "开始拍卖"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">出价：</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">选择拍卖物品：</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "出价人："))
        self.label_9.setText(_translate("MainWindow", "出价："))
        self.bid_button.setText(_translate("MainWindow", "出价"))
        self.end_button.setText(_translate("MainWindow", "结束出价"))

